# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bf12b503a207c1ab52d4b2d43b4ba410a383ac69ed13006c751d2d02ee669cf5cb0783450b0a182be773af7fdcfc3cf0b586fbff88d6c35a18822bda00b48fa
  facebook_app_id: 817475181707225
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

test:
  secret_key_base: 0f18ddc7b081f802aa6576af54cc5ebb3380ff272c474b01c26978e4f66f18d8f08a37015e78ab5c2c8994f118a809c7cd6d60057e337c4b2b519c184e788dc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 817475181707225
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
